const orchids = [
  {
    id: '1',
    name: 'Hoya Orchid',
    rating: 5,
    isSpecial: true,
    image: '/img/lancamcu.jpg',
    color: 'pink',
    origin: 'Taiwan',
    category: 'Cattleya',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '2',
    name: 'Cattleya Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lancattleya.jpg',
    color: 'white',
    origin: 'Thailand',
    category: 'Cattleya',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '3',
    name: 'Chu Dinh Orchid',
    rating: 4,
    isSpecial: true,
    image: '/img/lanchudinh.jpg',
    color: 'white',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: false,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '4',
    name: 'Dendro Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/landendro.jpg',
    color: 'purple',
    origin: 'Thailand',
    category: 'Dendrobium',
    isNatural: false,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '5',
    name: 'Hac Vy Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanhacvy.jpg',
    color: 'white',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '6',
    name: 'Hoang Lap Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanhoanglap.jpg',
    color: 'yellow',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '7',
    name: 'Flat Kieu Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lankieudet.jpg',
    color: 'white',
    origin: 'Thailand',
    category: 'Dendrobium',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '8',
    name: 'Mokara Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanmoraka.jpg',
    color: 'red',
    origin: 'Thailand',
    category: 'Mokara',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '9',
    name: 'Ngoc Diem Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanngocdiem.jpg',
    color: 'white',
    origin: 'Vietnam',
    category: 'Rhynchostylis',
    isNatural: false,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '10',
    name: 'Phi Diep Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanphidep.jpg',
    color: 'purple',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '11',
    name: 'Tam Bao Sac Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lantambaosac.jpg',
    color: 'multi-color',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: false,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '12',
    name: 'Tran Mong Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lantranmong.jpg',
    color: 'white',
    origin: 'Vietnam',
    category: 'Dendrobium',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '13',
    name: 'Vanda Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanvanda.jpg',
    color: 'blue',
    origin: 'Thailand',
    category: 'Vanda',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '14',
    name: 'Dancing Lady Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanvunu.jpg',
    color: 'yellow',
    origin: 'Thailand',
    category: 'Oncidium',
    isNatural: false,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '15',
    name: 'Chicken Thigh Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/landuiga.jpg',
    color: 'white',
    origin: 'Thailand',
    category: 'Cattleya',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  },
  {
    id: '16',
    name: 'Pearl Chain Orchid',
    rating: 4,
    isSpecial: false,
    image: '/img/lanchuoingoc.jpg',
    color: 'white',
    origin: 'Vietnam',
    category: 'Cattleya',
    isNatural: true,
    clip: "https://www.youtube.com/embed/jE-uqe8dSLU"
  }
];

export default orchids;
